<VirtualHost *:80>
	
	ServerAdmin support@MHOSTNAME
	ServerName VHOSTNAME

	DocumentRoot /Users/USERNAME/Sites/VHOSTNAME

	<Directory /Users/USERNAME/Sites/VHOSTNAME>

		Options Indexes FollowSymLinks ExecCGI MultiViews
		AllowOverride All
		Order Allow,Deny
		Allow From All

	</Directory>

	ErrorLog /Users/USERNAME/Sites/logs/vhosts/VHOSTNAME-error.log

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog /Users/USERNAME/Sites/logs/vhosts/VHOSTNAME-error.log combined

</VirtualHost>
